# Generated by Django 2.2.3 on 2019-07-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hmtl',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
    ]
