# Generated by Django 2.2.3 on 2019-07-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blog_hmtl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='hmtl',
            new_name='html',
        ),
    ]
